### PR TITLE
PLATOPS-1621 crypto upgrade to get bcprov-jdk15on 1.60.

### PR DESCRIPTION
**Pull request by jm2dev**

### CODE REVIEW

File: src/main/scala/uk/gov/hmrc/play/bootstrap/config/CryptoValidation.scala [hunk 1]
```diff
@@ -17,10 +17,9 @@
 package uk.gov.hmrc.play.bootstrap.config
 
 import javax.inject.Inject
-
 import play.api.Configuration
-import uk.gov.hmrc.crypto.ApplicationCryptoDI
+import uk.gov.hmrc.crypto.ApplicationCrypto
 
 class CryptoValidation @Inject()(configuration: Configuration) {
```
Comment (konradwudkowski) [inline src/main/scala/uk/gov/hmrc/play/bootstrap/config/CryptoValidation.scala]: you could also inject `ApplicationCrypto` directly instead of `Configuration`

File: src/test/scala/uk/gov/hmrc/play/bootstrap/config/CryptoValidationSpec.scala [hunk 2]
```diff
@@ -17,23 +17,26 @@
...
   "CryptoValidation" must {
 
     "Be created successfully if crypto configuration is valid" in {
-      new CryptoValidation(
-        Configuration(
-          "cookie.encryption.key"         -> "gvBoGdgzqG1AarzF1LY0zQ==",
-          "queryParameter.encryption.key" -> "gvBoGdgzqG1AarzF1LY0zQ==",
-          "sso.encryption.key"            -> "P5xsJ9Nt+quxGZzB4DeLfw=="
-        ))
+      import collection.JavaConversions._
```
Comment (konradwudkowski) [inline src/test/scala/uk/gov/hmrc/play/bootstrap/config/CryptoValidationSpec.scala]: I personally prefer collection.JavaConverters._ for reasons explained here: https://stackoverflow.com/a/8302493 and also because `JavaConversions` is deprecated in scala 2.12 https://www.scala-lang.org/api/2.12.7/scala/collection/JavaConversions$.html

File: src/test/scala/uk/gov/hmrc/play/bootstrap/config/CryptoValidationSpec.scala [hunk 3]
```diff
@@ -17,23 +17,26 @@
...
+      val mapa = Map(
```
Comment (konradwudkowski) [inline src/test/scala/uk/gov/hmrc/play/bootstrap/config/CryptoValidationSpec.scala]: typo in `map`

**Comment by konradwudkowski** [comment]
Is this a breaking change? Is code going to stop compiling for some teams that used the prev implementation of `crypto` and got it via bootstrap?

File: src/test/scala/uk/gov/hmrc/play/bootstrap/config/CryptoValidationSpec.scala (hunk 3 above)
Comment (jm2dev) [reply src/test/scala/uk/gov/hmrc/play/bootstrap/config/CryptoValidationSpec.scala]: I have a bad practice of naming short life variables in Spanish. I'll change it.

File: src/test/scala/uk/gov/hmrc/play/bootstrap/config/CryptoValidationSpec.scala (hunk 2 above)
Comment (jm2dev) [reply src/test/scala/uk/gov/hmrc/play/bootstrap/config/CryptoValidationSpec.scala]: Updated.

File: src/main/scala/uk/gov/hmrc/play/bootstrap/FrontendModule.scala [hunk 4]
```diff
@@ -31,7 +31,7 @@ class FrontendModule extends BootstrapModule {
     super.bindings(environment, configuration) ++ Seq(
       bind[AuditFilter].to[FrontendAuditFilter],
       bind[SessionCookieCrypto].toProvider[SessionCookieCryptoProvider],
-      bind[ApplicationCrypto].to[ApplicationCryptoDI],
+      bind[ApplicationCrypto].to(new ApplicationCrypto(configuration.underlying)),
```
Comment (konradwudkowski) [inline src/main/scala/uk/gov/hmrc/play/bootstrap/FrontendModule.scala]: you could change `to` to `toInstance` to only create a single instance of `ApplicationCrypto`

File: src/main/scala/uk/gov/hmrc/play/bootstrap/config/CryptoValidation.scala (hunk 1 above)
Comment (jm2dev) [reply src/main/scala/uk/gov/hmrc/play/bootstrap/config/CryptoValidation.scala]: Done.

**Comment by jm2dev** [comment]
After publishing locally an artifact to be used on eacd-support-frontend successfully, we think it shouldn't introduce breaking changes.

**Comment by konradwudkowski** [comment]
Is this line going to compile if a team upgrades bootstrap-play-25?
https://github.com/hmrc/mobile-messages/blob/ac6da7e3dae1e7eeddc1bdeed41778c157f36b8a/app/uk/gov/hmrc/mobilemessages/connector/SessionCookieEncryptionSupport.scala#L31

**Comment by jm2dev** [comment]
Well, it's already failing to compile for 3.11.0 and I was working on 3.15.0, I guess it seems potential issues weren't addressed before. I can take the chance to fix it, but this PR doesn't introduce compilation errors on `mobile-messages` for the first time.

**Comment by jm2dev** [comment]
After the compilation errors found in `mobile-messages` repo, we agreed on set major version to 4.
